src/index.js
test/jsx.js

Fix jsx renderer double closing elements

---

src/jsx.js

Fix dangerouslySetInnerHTML in JSX mode (Fixes #42)

---

src/index.js

Fix {nodeName:undefined} rendering [object Object] (fixes #38)

---

src/util.js
test/render.js

- mimick preact behaviour
- fix developit/preact-render-to-string#58

[feature] replace `undefined` prop values with defaultProps

---

test/render.js

I understand the preact-x branch is just a draft but this PR fixes all the failing tests.
The only fixes that are looking suspicious are those one: `match.falsy`. The state appear to be null sometimes

Get all tests passing

---

src/index.js
test/render.js

Fix hooks not working

---

src/index.js
test/pretty.js
test/render.js
test/shallowRender.js

Add support for Fragments

---

src/index.js
test/render.js

Fix select value not marking option as selected

---

src/index.js

Fixes https://github.com/preactjs/preact/issues/1728
_Note the existing tests fail as soon as the preact dependency is updated locally._

Fix options.render is private in core

---

package.json
src/index.d.ts
test/preact-render-to-string-tests.tsx
tsconfig.json

Added type definition tests

---

package.json

```
- Fix pretty option doing nothing (#106, thanks @marvinhagemeister)
- Added type definition tests (#83, thanks @9renpoto)
- [TS] Make options optional (#101, thanks @andrewiggins)
```

Release 5.0.5

---

src/index.js
test/jsx.js
test/pretty.js

I think I got it for real this time :+1: :100:  Combined the ideas in #103 + #102 and all tests pass. Linked it into `preact-markup` and the tests are now passing there too with the changes in this PR :tada:

Join adjacent text nodes

---

src/index.js
test/render.js

Not sure if I missed any edge case but the tests are all passing.

Indent Fragment's children when pretty printing.

---

package.json

:tada: 
- Indent `Fragment`'s children when pretty printing. (#117, thanks @utkarshkukreti)
- Initialize component `state` as an empty object (#119, thanks @marvinhagemeister)
- Streamline non-dimensional params with preact X (#111, thanks @JoviDeCroock)

Release 5.0.7

---

src/index.js
test/context.js

Fix missing context with contextType for class components

---

package.json
src/index.js
test/render.js

Fix effects breaking in SSR due to missing _renderCallbacks

---

src/index.js
test/render.js

Fix exception when invoking setState in cWM

---

package-lock.json
package.json

Release 5.1.5

---

src/index.d.ts
src/index.js
test/index.js

Remove unnecessary line

---

package-lock.json
package.json

- Fix node 14 compatibility with #134 .

Release 5.1.7

---

src/index.js
test/render.js

convert "htmlFor" to "for"

---

package-lock.json
package.json

Release 5.1.8

---

src/index.js
test/index.js

Follow up of #133 with tests (took way too long 🤣 )

Export renderToString as renderToStaticMarkup

---

src/index.js
test/render.js

Keep state changes during getDerivedStateFromProps

---

src/index.js
test/render.js

Add voidElements config option

---

src/index.js
test/render.js

This fixes preactjs/preact#2556.

Fix SSR for <textarea value>

---

package-lock.json
package.json

Release 5.1.10

---

package-lock.json
package.json
src/index.d.ts
src/index.js
src/jsx.d.ts
src/jsx.js
src/polyfills.js
src/util.js
test/context.js
test/index.js
test/jsx.js
test/pretty.js
test/render.js
test/shallowRender.js

This was long overdue!
1. Commit adds `prettier` + `lint-staged` + `husky`
2. Commit applies formatting to repo

Add prettier setup

---

benchmarks/index.js
benchmarks/isomorphic-ui-search-results/Footer.js
benchmarks/isomorphic-ui-search-results/SearchResultsItem.js
benchmarks/isomorphic-ui-search-results/data.js
benchmarks/isomorphic-ui-search-results/index.js
benchmarks/isomorphic-ui-search-results/search-results-data.json
benchmarks/stack.js
benchmarks/text.js
package-lock.json
package.json

This PR adds two simple benchmarks to get the ball rolling.

Add some simple Benchmarks

---

.changeset/brown-fishes-exercise.md
package-lock.json
package.json
src/index.js
src/util.js
test/compat.test.js
test/render.test.js

We're rolling out our experimental v11 version, which switches us from storing everything on vnode/component to an internal

Support preact v11

---

.changeset/twenty-weeks-fetch.md
src/index.js
test/render.test.js

Don't add selected attribute to <option> if it already exists

---

.changeset/fresh-plums-wave.md
package.json

Only one of those is needed. See: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Remove duplicate type path in package.json

---

.changeset/honest-kangaroos-mix.md
src/index.js
test/render.test.js

The revised calling order now exactly matches Preact core (diff -> children -> diffed).
I also added some comments to the pieces of renderToString.

Fix options hook calling order

---

.changeset/breezy-avocados-call.md
.changeset/hungry-rules-itch.md
src/index.js

This so we correctlly unmount hooks/signals/....

correctly unmount vnodes

---

.github/workflows/ci.yml
.github/workflows/release.yml

1. update actions/checkout to v3
2. update actions/cache to v3

ci: update github actions

---

.changeset/perfect-ducks-rule.md
src/index.js
test/render.test.js

Fixes https://github.com/preactjs/preact-render-to-string/issues/271

support data attribute

---

.changeset/beige-starfishes-worry.md
src/util.js
test/render.test.js

avoid adding double colon

---

.github/workflows/release.yml
package.json

I will be generating a token that is valid for a year, scoped to only this repository

chore: automate publishing with provenance

---

.changeset/clever-kings-brush.md
config/node-commonjs.js

Fixes https://github.com/preactjs/preact-render-to-string/issues/343

ensure the cjs export has our async func

---

.editorconfig

Copied from core, I have to keep rewriting all my 4-space tabs w/out this 😅

chore: Add editorconfig
