src/index.js
test/render.js

To ensure this behaves the same as `preact` I just brought over and updated the relevant tests from there. Happy to make any alterations.

Fix issue where child context was replacing instead of augmenting parent context

---

src/index.js
test/render.js

Hello! XLink attributes on SVG elements don't seem to be transformed. For example `<use xlinkHref="#foo">` is being rendered as-is, when Preact renders it (correctly) as `<use xlink:href="#foo">`.
I'm going to attempt to fix it myself, but in the meantime please enjoy this failing test case:
```
1) render Basic JSX should render SVG elements:
AssertionError: expected '<svg viewBox="0 0 360 360"><use xlinkHref="#foo"></use></svg>' to equal '<svg viewBox="0 0 360 360"><use xlink:href="#foo"></use></svg>'
+ expected - actual
-<svg viewBox="0 0 360 360"><use xlinkHref="#foo"></use></svg>
+<svg viewBox="0 0 360 360"><use xlink:href="#foo"></use></svg>
at Context.<anonymous> (test/render.js:79:24)
```

SVG XLink attributes are rendered incorrectly

---

src/index.js
test/jsx.js

[React supports](https://facebook.github.io/react/docs/react-component.html#render) returning `null` or `false` from a render function to indicate nothing to render.
Currently returning false during a server render will render the string ‘false’. 
As we use inline conditional rendering quite heavily e.g. `return condition && <div>yo</div>`this is causing our server renders with `preact-compat` to surface a fair amount of these unwanted strings.

Render empty value if render returns false

---

src/index.js
test/pretty.js
test/render.js

This fixes https://github.com/developit/preact-render-to-string/issues/24 by closing void element tags with a `/`. It updates relevant tests accordingly.

Close void tags with slashes to support XHTML

---

src/util.js
test/render.js

Currently an empty styles object will server render the style attribute e.g. `<div style></div>` when what we really want is `<div></div>`. This is a slight inconsistency with React (and I think Preact?). 
This sounds quite benign but as we don't allow inline styles in our CSP rules the addition of this attribute is quite major.. especially as React Router's `Link` seems to default this to an empty object.

When styles object is empty don’t render style attribute

---

package.json
src/index.d.ts
typings.json

- Try to mimic the Preact TSD.
- Example usage with `noImplicitAny` enabled:
import { render } from "preact-render-to-string";
- No idea if I've done it right but it seems to compile and hopefully
someone more knowledgeable can build on this.

New: add TypeScript definitions

---

src/index.js

The logic was really just incorrect, `displayName` and `name` will only ever exist on a component's constructor, not the prototype or instance.

Correct & simplify component name detection (Fixes #44)

---

src/index.js
test/render.js

Addresses Issue https://github.com/developit/preact-render-to-string/issues/62 by adding support for `getDerivedStateFromProps` which takes precedence over `componentWillMount`.
**`npm run build` (Before)**
> Build "preactRenderToString" to dist:
>       1.41 kB: index.mjs
>       1.45 kB: index.js
**`npm run build` (After)**
> Build "preactRenderToString" to dist:
>       1.45 kB: index.mjs
>       1.49 kB: index.js
Support was added to Preact with this PR https://github.com/developit/preact/pull/1094

Adds support for `getDerivedStateFromProps`

---

package.json

This PR changes the external option for the build script from `none` to `preact` which resolves the crash when using hooks. (https://github.com/developit/preact/issues/1373)
The test for hooks ran fine when using the `src`, but crashed when using `dist` (the __h of undefined error). The reason for this was that with external option set to `none` resulted in the imported options from preact being an empty object (so `options.render` would not be called and hooks would crash). 
https://github.com/developit/preact-render-to-string/blob/8536c758e3d1808bcc18d64cd944da609531d11e/src/index.js#L66
Result difference in build:
**Before:** 
`1510 B (mjs)`
`1567 B (js)`
**After:**
`1487 B (mjs)`
`1549 B (js)`
**Difference:**
`-23 B (mjs)`
`-18 B (js)`

Resolve crash when using hooks

---

src/index.js
test/context.js

Adds support for createContext introduced by preact x.
I'm not sure whether these checks should also be introduced for class components. As the context consumer is currently a functional component it is sufficient to add the checks for these.
Fixes #73

Support createContext of preact x

---

src/index.js
test/render.js

This fixes the issue described in #95 by wrapping any arrays passed to renderToString in Fragment

Wrap arrays in Fragment to allow proper rendering

---

package.json

- Fix `options.render` is private in core (#97, thanks @marvinhagemeister)
- Wrap arrays in `Fragment` to allow proper rendering (#96, thanks @toraora)

Release 5.0.4

---

src/index.d.ts

Make each Option property optional to allow passing in partial options objects (e.g. `{ pretty: true }`)

[TS] Make options optional

---

env.js
package.json
src/index.js

This PR removes a global flag which removed pretty-printing during the compilation step. Not sure why this code was even there in the first place. Because of that this issue only occured with the transpiled bundle.
Fixes #105 .

Fix pretty option doing nothing

---

package.json

This PR fixes 2 deprecation warnings:
- Mocha `compilers` options is deprecated
- Fix eslint warning `No react version specified`

Fix build tools deprecation warnings

---

src/index.js
test/render.js

This PR makes sure that we initialize `component.state` as an empty `object` like we're [doing over at Preact](https://github.com/preactjs/preact/blob/2f0555878b1b435dbe148d5fe88908a45d2cb624/src/diff/index.js#L63).
Fixes #118 .

Initialize component state as an empty object

---

src/index.js

Always throw errors, not strings. Fixes #68

Always throw errors, not strings

---

src/index.js
test/context.js

Issue here was that the [mangled `_defaultValue`](https://github.com/preactjs/preact/blob/71425ff63ddd59989a7c657f659b70960d457600/mangle.json#L36) prop wasn't being used. 😱
Pretty edge case for _most_ libraries I suppose, which is why it might not have been caught yet

Fix support for default context value

---

jsx.d.ts
package.json
src/jsx.d.ts

This PR adds the TypeScript definitions for `preact-render-to-string/jsx`.

Add TypeScript definitions for JSX renderer

---

README.md

This fixes the build status badge from `unknown` to `passing`.

Update Travis CI org name to `preactjs` [skip ci]

---

src/index.js

This prevents hook update methods from erroring, which often looks like the following:
```
TypeError: o.__c.setState is not a function
at QueryData.o.__c.o.__ [as forceUpdate
```
This still ensures state mutations have no effect during SSR, but allows the following code to execute without causing an exception after rendering has occurred and `pending` resolves:
```js
import { useState, useMemo } from 'preact/hooks';
function Resolve({ promise }) {
const [value, setValue] = useState(undefined);
const pending = useMemo(() => promise.then(setValue), [promise]);
return value;
}
```

Add setState()/forceUpdate() no-op methods to prevent errors

---

package.json

I think we could land this as a patch since it only drops support for alpha versions.

Preact>=10 peer dep

---

config/node-13-exports.js
package.json

In Node v13, package exports were introduced as an official way to define sub-paths/modules within your package: https://nodejs.org/api/esm.html#esm_package_exports
Fixes #144 .

Add submodule exports

---

src/util.js
test/render.js

```js
// before
styleObjToCss({ '--numStars': 5 })  // "--num-stars: 5;"
// after
styleObjToCss({ '--numStars': 5 })  // "--numStars: 5;"
```

Fix accidental camelCasing of CSS Variables

---

src/index.js
test/render.js

Fixes #4 (at least for aria-* attributes)

Stringify boolean aria-* attributes

---

src/index.js
test/render.js

Omit defaultValue attribute to render AMP compliant HTML

Omit defaultValue attribute

---

src/index.js
test/render.js

If an element that is typically a void element is being used as a standard element with children, don't self close it.
The existing test for this was not doing what its description said.  This is required for better xml support. See #53

[bugfix] do not close void elements with a closing tag

---

package.json
src/util.js

See benchmarks:
https://esbench.com/bench/5f88af6cb4632100a7dcd414
`Scan (str) [3]` is this revised implementation, which is 50% faster than the previous implementation (`replace`).

Optimize HTML entity encoding

---

package.json
src/index.js
test/render.js

As otherwise `preact/debug` throws errors when using hooks as `hooksAllowed` is never set to `true`.
I could not yet come up with a test repro for this though!

Invoke _diff hook

---

src/index.js
test/render.js

This change prevents to self-close if the element has `dangerouslySetInnerHTML` prop. This is required for better xml support.
Currently behavior:
```
import { h } from 'preact'
import renderToString from 'preact-render-to-string'
console.log(renderToString(<a dangerouslySetInnerHTML={{ __html: '<b />' }}></a>, undefined, { xml: true }))
// <a><b / />
console.log(renderToString(<link dangerouslySetInnerHTML={{ __html: '<foo />' }}></link>))
// <link><foo / />
```

Prevent to self-close if dangerouslySetInnerHTML set

---

package-lock.json
package.json
src/index.js
test/render.js

We never called `options.diffed` and `options._commit` during SSR. Looks like we forgot to add those.
Resolves a part of the issue mentioned at https://github.com/preactjs/preact/issues/2574

Fix options.diffed and options._commit never being called

---

src/util.js

This change significantly speeds up entity ecoding making it 170 ops/sec faster than before. Benchmark: https://github.com/marko-js/isomorphic-ui-benchmarks
Machine: Macbook Air M1
Before: `851 ops/sec`
After: `1,027 ops/sec`
Fixes: #180

Perf: Improve HTML entity escaping

---

config/node-commonjs.js
package.json

A recent dependency update changed the exported values in our `commonjs` entries by exposing both the `default` export and `named` exports. This commit ensures that we're always using the default export and ignore any named ones.
Regardless of whether the new behaviour is the preferred one, we should not do such breaking changes in a patch release.
Fixes #182

Revert back to old commonjs behaviour.

---

src/index.js
src/util.js

A good chunk of serverside rendering is spent escaping strings. There is a high likelyness, that we'll see the same strings over and over again. By memoizing those computations we get a nice speedup. A tiny bit more (at least in benchmarks) can be achieved by hoisting out regex creation.
| Benchmark | before (ops/sec) | after (ops/sec) |
|---|---|---|
| Text | 260.183 | **401.336** |
| SearchResults | 637.04 | **730.82** |

Performance: Memoize entity encoding

---

src/util.js

This reverts commit f5bae9ea9c3e30793e83a3f50a0172bae614ae2c.
Because we cannot forsee the length and amount of strings we need to be more careful about keeping them around as memory consumption can grow unbounded. In the future we should check if we can use a limited cache, only cache attributes or something else. WeakMaps unfortunately won't help as they cannot be used with primitives as cache key.
Got notified privately that a production site ran into a memory leak and we definitely don't want that. Let this be a lesson for myself to be sceptical of memoization, despite it being an easy way to improve benchmark scores!

Revert "Memoize entity encoding"

---

.gitignore
benchmarks/index.js
benchmarks/lib/benchmark-lite.js
benchmarks/lib/render-to-string.js
package.json

This updates the benchmarks to run against a previous known good state (preact-render-to-string@5.1.16), which makes them resilient to machine & time differences (similar to our tach setups).
It also adds a second `d8`-based benchmark runner based on the same code, using a crappy version of benchmarkjs I wrote.

Benchmark runner updates

---

src/index.js
src/util.js

Some benchmarks, for reference:
https://esbench.com/bench/5f88af6cb4632100a7dcd414

Performance improvements!

---

src/util.js

This pull request attempts to optimize util.js's `encodeEntities` function. This happens by skipping the `.replace(...)` chain for inputs that contain no characters that should be replaced.
The benchmarks seem get a boost from this (Node v14.16.0, Linux, x86), especially the SearchResults one. Here are the `npm run bench` results before this change:
```
Text:
baseline x 80.883 ops/sec ±1.16 (67 runs sampled)
current x 94.593 ops/sec ±2.36 (73 runs sampled)
SearchResults:
baseline x 404.532 ops/sec ±2.42 (79 runs sampled)
current x 448.104 ops/sec ±2.61 (83 runs sampled)
```
And after this change: 
```
Text:
baseline x 83.055 ops/sec ±1.54 (68 runs sampled)
current x 103.134 ops/sec ±1.95 (74 runs sampled)
SearchResults:
baseline x 453.03 ops/sec ±2.13 (84 runs sampled)
current x 648.997 …
```

Add encodeEntities fast path for inputs that don't need anything replaced

---

src/index.js

This skips effects during `renderToString` just like React, as this function runs synchronously anyway and isn't subject to effectful rerenders.
Fixes: https://github.com/preactjs/preact-render-to-string/issues/191

Skip effects during RTS

---

src/index.js

I believe this may be the root cause of the remaining memory leak in #191.

Bugfix: Prevent infinite render queue array growth

---

package.json

Preact was bundled into our jsx renderer leading for `preact.options` to be inlined. That broke hooks for the jsx renderer.

Fix preact being accidentally inlined for jsx renderer

---

src/index.js
test/render.test.js

h/t @washingtonsteven who found this
This is sortof a follow-up to the patch from #163 - we shouldn't serialize `defaultValue` as `defaultValue`, but instead omitting it we should serialize to the `value` attribute (which is effectively the same as the `defaultValue` property).

Fix: serialize defaultValue as value attribute

---

.changeset/fifty-rings-jog.md
package.json
src/index.js
test/compat.test.js

Fixes #208
Empty `props.class` wouldn't be truthy, resulting in `class` being added to the element twice as outlined in the attached issue.
The added test might be a bit overkill, but it seems Mocha has no support for test isolation. Importing `preact/compat` (even in other suites) would throw off one of the existing tests, so I just run the compat suite subsequently. Let me know if there's a better way to go about this.

fix: On empty className w/ compat, class attr will no longer be duplicated

---

README.md

This project hasn't been using Travis CI since it switched to GitHub Actions in
https://github.com/preactjs/preact-render-to-string/pull/179 (Feb 2021), but the
README still shows the old Travis CI badge which currently shows build status as
"failing".

Update Travis CI badge to GitHub Actions [skip ci]

---

.changeset/chilly-ligers-agree.md
src/index.js
test/render.test.js

This implements hooks state "settling", where a function component that invokes setState/forceUpdate during rendering is re-invoked up to 25 times or until it stops invalidating during invocation.
The implementation here is for Preact 10, and will need to be updated to use Internal.flags in Preact 11 (however RTS is moved to core in 11).
Fixes #218.

Implement hook state settling

---

.changeset/twelve-kiwis-tap.md
src/index.js

Uses a smarter stringbuilder props to @developit https://esbench.com/bench/5c7aaeef4cd7e6009ef6217c

chore: do several perf improvements

---

.changeset/orange-poems-learn.md
src/util.js

Entity encoding is a large portion of time spent, since we encode all attribute values and text nodes.
This switches encoding from multiple regular expressions to a linear forward scan.
In [the benchmark below](https://esbench.com/bench/5f88af6cb4632100a7dcd414), the previous algorithm is the second bar ("replace"), and the new algorithm is the last bar ("scanSegments 2"):
**Note:** This doesn't show up in our two benchmarks here, because there are no entities present in the text or attributes in those benchmarks.

[perf] Improve string encoding performance by ~50%

---

.changeset/silly-masks-jump.md
package-lock.json
package.json
src/index.js
src/util.js

This PR aims to create as many hot paths as possible, we went from being slower than react 18 string rendering to
```
Running "search-results"...
Running benchmark "preact"...
preact x 1,003 ops/sec ±1.53% (88 runs sampled)
Running benchmark "react"...
react x 1,127 ops/sec ±6.13% (76 runs sampled)
--------------
Running "color-picker"...
Running benchmark "preact"...
preact x 5,513 ops/sec ±0.29% (93 runs sampled)
Running benchmark "react"...
react x 5,829 ops/sec ±8.04% (79 runs sampled)
--------------
```
```
Running "search-results"...
Running benchmark "preact"...
preact x 1,437 ops/sec ±1.56% (93 runs sampled)
Running benchmark "react"...
react x 1,235 ops/sec ±5.94% (82 runs sampled)
--------------
Running "color-picker"...
Running benchmark "preact"...
preact x 7,862 ops/sec …
```

[perf] split out pretty and create hot paths

---

.changeset/dull-baboons-kneel.md
.changeset/young-cougars-protect.md
src/constants.js
src/index.js

In action: https://codesandbox.io/s/crazy-platform-omyl5l?file=/src/renderToString.js
Supersedes https://github.com/preactjs/preact-render-to-string/pull/226
used for https://github.com/preactjs/preact/pull/3583

add parent and children for useId

---

.changeset/curly-bananas-do.md
src/index.js
src/pretty.js
test/jsx.test.js
test/pretty.test.js
test/render.test.js

Ignore non-VNode objects during rendering

---

.changeset/few-elephants-occur.md
package-lock.json
package.json
src/index.js
test/render.test.js

With https://github.com/preactjs/preact/pull/3758 we need to include `Fragments` when setting masks. But core has an optimization where we flatten a `Fragment` when it's the top level node of the return value of a component.
```jsx
function Foo() {
// Will be flattened
return <Fragment>...</Fragment>
}
```

Fix useId mismatch due to top level Fragments

---

README.md

Some `README` changes:
- Use named exports instead of default export. We might want to drop the default export at some point
- rest is prettier changes when saving the file

Use named exports in README

---

package.json

When working on `preact-render-to-string` I find myself manually building the test command for watch usage. This PR rewrites our test scripts so that we can pass `--watch` to both `test:mocha` and `test:mocha:compat` to enable watch mode.

Update test scripts to allow watch usage

---

.changeset/brown-boats-nail.md
package.json
src/index.js
test/debug.test.js

Normalize text vnodes for `preact/debug`

---

src/client.js
src/index.d.ts
src/index.js
src/stream-node.js
src/stream.js
test/compat-render-chunked.test.js
test/compat-stream-node.test.js
test/compat-stream.test.js

Summary:
- use comments to denote placeholders to not break semantic HTML structures
- use a custom-element to handle moving into place
- this remove the need for a mutation observer
- seems like a cool use of a ce and I figured why not? should probably perf test it though
- adds onError for the underlying renderToChunks implementation
- adds renderToPipeableStream

feat: use comments instead of element as marker

---

.changeset/soft-badgers-clap.md
src/index.js

This is a tiny performance improvement for unmount option hook.

Unmount option hook call performance

---

README.md

Lazy component documentation

---

.changeset/fluffy-poets-happen.md
src/util.js

Follow up to #278 @andrewiggins thank you for the feedback

Follow up fixes

---

.changeset/gentle-trains-attack.md
src/index.js
test/render.test.js

Marked as major in case people rely on this for tests
Fixes #279

Remove trailing space for void elements

---

.changeset/curvy-rings-invent.md
config/node-commonjs.js
config/node-verify-exports.js
package-lock.json
package.json
src/index.d.ts
src/index.js
src/jsx.d.ts

We removed a couple named exports in `6.0.0`, but it turns out that this clashes with a couple of libraries in the Preact ecosystem that we use. This PR brings back all the missing exports, with the exception of `shallowRender` which was moved to `preact-render-to-string/jsx` in `6.0.0`.
On top of that I added a quick script to verify that all of them work to prevent such issues in the future.
Fixes #290

Bring back missing exports from 5.x

---

.changeset/mean-coins-move.md
package.json

Fixes: https://github.com/preactjs/preact-render-to-string/issues/297
When I build the following code with the tsc command, I get an error message.
```
import { shallowRender } from 'preact-render-to-string/jsx';
import {h} from "preact";
const Sample = () => <div>sample</div>
shallowRender(<Sample />);
```
The error message is as follows
```
❯ tsc -p tsconfig.json --strict
src/index.tsx:1:31 - error TS7016: Could not find a declaration file for module 'preact-render-to-string/jsx'. '/Users/shinyama-k/preact-render/node_modules/preact-render-to-string/jsx.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/preact-render-to-string` if it exists or add a new declaration (.d.ts) file containing `declare module 'preact-render-to-string/jsx';`
1 import { shallowRender } from …
```

Fix to add type file for jsx.js

---

src/index.js
src/jsx.js
src/pretty.js
test/compat/index.test.js
test/context.test.js
test/debug/index.test.js
test/index.test.js
test/jsx.test.js
test/preact-render-to-string-tests.tsx
test/pretty.test.js
test/render.test.js
test/shallowRender.test.js

Deno uses ESM resolution internally which requires file extensions, similar proper ESM in node and browsers. These changes shouldn't have any effect on the distributed package as we flatten the code to a single file before publish.

Add support for linking to Deno projects

---

.changeset/shy-hotels-impress.md
src/index.js
test/render.test.js

This PR adds support for rendering HTML comments via `preact-render-to-string`. Instead of adding a new vnode type this leverages `Fragments`. This has the benefit that branching cost is minimal as `Fragments` are the least frequently used components and they sorta represent "nothing" in terms of client code.
`<Fragment UNSTABLE_comment="foobar" />` renders ``. When the prop is present, all other children are ignored.
This solves an issue with fresh which currently renders invalid HTML comments. Browsers happily parse over that, but it's annoying if you're testing with HTML validators on CI. See https://github.com/denoland/fresh/issues/838

Add support for rendering HTML comments

---

.changeset/cold-otters-argue.md
README.md
src/index.js
test/render.test.js

This PR adds support for error boundaries by supporting `componentDidCatch` and `getDerivedStateFromError`. To make this a non-breaking change this feature is disabled by default. It can be turned on by setting `options.errorBoundaries = true`.
This work is based on #66 and #67 .

Add support for `componentDidCatch` + `getDerivedStateFromError`

---

.changeset/five-stingrays-return.md
src/index.js
test/render.test.js

Resolves the remaining scenarios mentioned in #307 .

Fix incorrect namespaced attributes rendering

---

.changeset/dull-jobs-sin.md
src/index.js
test/render.test.js

This PR adds support for the new precompile JSX transform that will ship with the next deno version. The new deno version will come out this week.
The idea behind the precompile JSX transform is that instead of allocating a full vnode object + props for every element, we precompile HTML nodes during the JSX transpilation step to strings. During rendering we then need to mostly only concatenate strings together.
Demo: https://github.com/marvinhagemeister/deno-jsx-precompile-preact-demo

feat: add support for precompiled JSX

---

.changeset/hip-beers-speak.md
src/index.js
test/render.test.js

This fixes an issue with Deno's new JSX precompile transform. The child expressions can also contain an Array in situations like this:
```jsx
<ul>
{[1,2,3].map(x => <li key={x}>{x}</li>)}
<li>4</li>
</ul>
```
...which is transformed to something lie this:
```jsx
const tpl = [
"<ul>", "<li>4</li></ul>"
]
jsxTemplate(tpl, jsxEscape([1,2,3].map(x => ...)))
```
This case wasn't considered during rendering.

fix: mapped precompile children

---

.changeset/afraid-dolls-walk.md
src/index.d.ts

Ran into type errors when running the following:
```typescript
renderToString(h(RootComponent, null));
```
This PR should fix it.
After checking if this change has any runtime implications, it seems that only `Fragment`s are affected. So, I've added a fix for that as well. Not sure why anyone would want a `Fragment` with `null` props though.

fix external type definitions of `renderToString`

---

.changeset/early-rules-nail.md
jsx.d.ts

This PR fixes https://github.com/preactjs/preact-render-to-string/issues/328, by removing the second default export from `jsx.d.ts`

Remove incorrect second default export from jsx.d.ts

---

package-lock.json
src/index.js
test/compat/async.test.js

While I was working on a real-life application using lazy components (using `lazy` and `Suspense`) when I noticed that the rendered HTML sometimes contains `[object Promise]` instead of properly resolved component markup.
I did some debugging and I found out that this issue happens only when there are nested lazy components in the app (_App_ renders _ComponentA_ lazily, _ComponentA_ renders _ComponentB_ lazily), in this case _ComponentB_ is rendered as `[object Promise]`.
If I get it right, there is a test case for validating nested Suspense boundaries (`Async renderToString > should render JSX with nested suspense boundary`), but that test case does not contain nested Suspense boundaries, only a single Suspense boundary with multiple nested suspended components.
I think both use-cases …

Fixing nested Suspense boundaries in Simple Suspense Renderer

---

src/index.js
test/compat/async.test.js

Rendering a Suspense boundary which have multiple suspended components as children fails:
```ts
const promise = renderToStringAsync(
<ul>
<Suspense fallback={null}>
<SuspenderOne>
<li>one</li>
</SuspenderOne>
<SuspenderTwo>
<li>two</li>
</SuspenderTwo>
</Suspense>
</ul>
);
```
```
1) Async renderToString
should render JSX with multiple suspended direct children within a single suspense boundary:
Error: the promise {} was thrown, throw an Error :)
```
I was curious so I trying to debug and fix this, what I found is:
- `_renderToString` (with `asyncMode: true`) throws a Promise while rendering the children of a component, if any of the children is a suspended component
- in this case the error Promise is caught, and once it resolves the same render is called again (without the try-catch …

Fixing rendering multiple suspended components within one Suspense boundary

---

.changeset/cuddly-spoons-impress.md
src/index.js
test/compat/async.test.js
test/utils.js

When an error was thrown after suspending a component we didn't rethrow it. This lead to a cryptic `e.then is not a function` error instead of the expected error message.

fix: suspended error not re-thrown

---

README.md

We were still referencing `prepass` in our README instead of `renderToStringAsync`

chore: Update readme for suspense rendering

---

.changeset/proud-eyes-cheer.md
src/index.js
test/compat/async.test.js

We have lots of code in hooks that checks for this being `null` when empty. This broke with `preact-render-to-string` because we did set it to `undefined` on reset here and caused the `useId()` hook to throw an error.

fix: invalid `vnode._parent` value

---

.github/workflows/ci.yml
.github/workflows/release.yml

This pull request updates the actions/checkout and actions/setup-node actions from v3 to v4. The explicit actions/cache usage is removed, instead actions/setup-node's [builtin caching](https://github.com/actions/setup-node?tab=readme-ov-file#caching-global-packages-data) is used.

build(actions): update actions, use actions/setup-node's builtin caching

---

.changeset/nine-buckets-pull.md
src/index.js
test/render.test.jsx

Since we use a `Fragment` for the template we need to ensure that we don't fall into the logic where we detect if a component returned a top level `Fragment`.
This fixes an issue discovered when using Preact with Deno's `precompile` JSX transform.

fix: precompile template empty HTML

---

.changeset/perfect-hounds-joke.md
src/index.js

This removes a closure that isn't necessary when rendering vnode children.

perf: remove unnecessary closure

---

.changeset/fast-rockets-admire.md
src/pretty.js
test/shallowRender.test.jsx

fix: shallow render with fragment at top lvl

---

.changeset/yellow-ghosts-bow.md
src/index.js
test/render.test.jsx

Fixes #346
This also got reported as an issue on Slack

fix(core): render empty string for null __html

---

config/node-13-exports.js
config/node-commonjs.js
config/node-verify-exports.js
package-lock.json
package.json
test/preact-render-to-string-tests.tsx
tsconfig.json

Builds on top of #362-ish
Does a few things:
- Output in `dist/` is now nested per export
- Makes it so much easier to debug/deal with when the exports aren't all at same level.
- Simplifies & makes build scripts a tad more consistent
- Drops `pretty-format` dependency -- it's already inlined into the export that uses it. It's not a heavy dep, but entirely unused all the same.

refactor: Build scripts & output directories

---

.changeset/quick-goats-end.md
src/lib/client.js

fix: stop client runtime from being corrupted
This does two things
1.) the current logic to move OOO children doesn't support multiple children, and is kinda just wrong
2.) puts the client OOO runtime into a string to stop corruption by bundlers such as Vite

fix: insert ooo chunks in the proper order

---

.changeset/chilly-ladybugs-think.md
src/index.js
test/compat/async.test.jsx
test/render.test.jsx

fix: Support `dangerouslySetInnerHTML={undefined}` with `renderToStringAsync`

---

.changeset/calm-cherries-lay.md
benchmarks/index.js
package-lock.json
package.json
src/index.js
src/lib/util.js

- use an `EMPTY_STR` for coercion to reduce allocation of empty strings as well as for empty string checks
- only call `encodeEntities` when the entity in question is a string, this removes always calling the function _and_ an unnecessary coercion
- ensure we leverage `x = x + y` rather than `x += y`
- ensure we leverage our `isArray` helper
- guard for some code-paths that are only possible with i.e. a class-component (avoids expensive object checks)
- skip function type properties
Results from CI (locally saw a bit larger increases, maybe node version?)
```
Text:
baseline x 259.905 ops/sec ±2.52 (83 runs sampled)
current x 273.589 ops/sec ±2.15 (87 runs sampled)
Fastest is current
SearchResults:
baseline x 1,330.724 ops/sec ±3.20 (87 runs sampled)
current x 1,365.269 ops/sec ±2.88 (89 …
```

chore: general performance optimisations

---

.changeset/young-avocados-float.md
src/index.js
src/lib/util.js
test/render.test.jsx

Fixes https://github.com/preactjs/preact-render-to-string/issues/387

fix: wrong spellcheck attribute value

---

.changeset/metal-bottles-play.md
src/index.js
test/render.test.jsx

Seems fine to merge, but then again this seems cursed and I'm worried that this list will get longer. For now it seems fine though.
Fixes https://github.com/preactjs/preact-render-to-string/issues/390

fix: allow any stringified value in class + className

---

.github/workflows/ci.yml
package.json

Locally I was seeing some bizarre numbers for the "current" bench, about 50% faster. Took me a few minutes to realize I had an old build sitting around 😅 
I think this setup should work better? As the bench uses the built files from `/dist`, you'll always want to run a build whilst playing with the benchmarks. The tests themselves use the source files though, so they don't inherently need it.

chore: Run build prior to running benchmarks

---

.changeset/angry-chairs-marry.md
package-lock.json
src/index.js
src/lib/util.js
test/render.test.jsx
test/utils.jsx

Supports `spellcheck={false}` & removes support for `spellCheck` as we don't support it in Preact (see: https://github.com/preactjs/preact/issues/3399)
Related: #388, https://github.com/denoland/fresh/issues/2649, https://github.com/preactjs/preact/pull/4497
This adds a `HTML_ENUMERATED` rgx to stuff enumerated true/false attributes into in the future, as I brought up in #388.

fix: `spellcheck` prop

---

package-lock.json
package.json
test/compat/index.test.jsx

Workin' on the ecosystem CI, came across this.
The test case change is due to this: https://github.com/preactjs/preact/pull/3941/files#r1144722263

chore: Bump preact version

---

.changeset/kind-pumas-wash.md
src/lib/util.js

Should be marginally faster, and these patterns are all written for line start anyhow -- we don't intend to match `foobarbaztabIndex`.

refactor: Switch `HTML_LOWER_CASE` rgx to always match from line start

---

test/render.test.jsx

Randomly noticed an incorrect test assertion while looking through our tests. When you pass a regex to `.contain()` in `chai` it will cast it to a string and the rendered output does indeed not contain the string `/\s/`.
It should've been `.match()` instead. And because there is a space between an element name and an attribute, that needs to be removed too.

chore: fix test assertion

---

.changeset/giant-schools-explode.md
package-lock.json
src/index.js

```
Text:
baseline x 434.471 ops/sec ±2.09 (89 runs sampled)
current x 455.816 ops/sec ±1.35 (88 runs sampled)
Fastest is current
SearchResults:
baseline x 2,124.763 ops/sec ±3.50 (92 runs sampled)
current x 2,174.318 ops/sec ±4.29 (88 runs sampled)
Fastest is current
ColorPicker:
baseline x 12,934.781 ops/sec ±1.34 (95 runs sampled)
current x 13,121.543 ops/sec ±0.87 (97 runs sampled)
Fastest is current
```

improve perf with array pre-allocate

---

.changeset/little-rocks-doubt.md
src/stream-node.d.ts
src/stream.d.ts

Currently the `vnode` argument for these two functions always defaults to `VNode` (which defaults to `VNode<{}>`), this causes issues with *some* arguments that are otherwise valid (and run fine, it's purely a TypeScript typecheck issue).
```typescript
const Context = createContext({});
renderToPipeableStream(h(Context.Provider, { value: {} }), {});
```
```
/*
src/index.ts:6:24 - error TS2345: Argument of type 'VNode<Attributes & { value: {}; children?: ComponentChildren; }>' is not assignable to parameter of type 'VNode<{}>'.
Types of property 'type' are incompatible.
Type 'string | ComponentType<Attributes & { value: {}; children?: ComponentChildren; }>' is not assignable to type 'string | ComponentType<{}>'.
Type 'ComponentClass<Attributes & { value: {}; children?: ComponentChildren; …
```

Use generic type for vnode props in renderToReadableStream/renderToPipeableStream

---

.changeset/friendly-numbers-hang.md
src/index.js
src/internal.d.ts
src/lib/chunked.js
test/compat/render-chunked.test.js
test/compat/stream-node.test.js
test/compat/stream.test.js

Fixes https://github.com/preactjs/preact-render-to-string/issues/406

Use suspense boundary vnode as parent for subtree re-render

---

.changeset/friendly-numbers-hang.md
package-lock.json
src/index.js
test/compat/render-chunked.test.js
test/compat/stream-node.test.js
test/compat/stream.test.js

CC @f0x52 
Resolves https://github.com/preactjs/preact-render-to-string/issues/407
This avoids us nullifying the `parent` pointer which leads us to have unique id across streaming boundaries.
Tangent: I did think about https://github.com/preactjs/preact/issues/4442 and how currently in Preact we might not wait for a boundary to finish streaming in. Which might fallback to normal rendering if the JS bundle loads faster than the boundary streaming in, we might need to fix this as part of hydration 2.0 as well.

Ensure use id works

---

.changeset/mighty-keys-admire.md
src/stream-node.d.ts
src/stream-node.js

Fixes https://github.com/preactjs/preact-render-to-string/issues/404
Changes error and abort handling in `renderToPipeableStream` so the stream no longer emits an uncatchable error event. Instead errors are passed to `options.onError` if provided. If there is no error callback it's rethrown, though maybe that's not ideal since it happens in the async chain, so can't really be caught either. Alternatively this could just `console.error`, so it doesn't get silently swallowed entirely? 
Also added an optional `reason` argument for `stream.abort()`, defaulting to `new Error(The render was aborted by the server without a reason.)` inspired by React. Previously this was just `new Error('aborted')`, though this was never exposed to consumers.
Abort still destroys the stream, and also calls the …

renderToPipeableStream: Expose errors through onError, no longer emit un-catchable error event on internal stream

---

.changeset/happy-peas-type.md
src/index.js
test/compat/async.test.jsx

Relates to https://github.com/preactjs/preact/issues/4442
This adds the comments approach described in the RFC, these comments will be used with resumed hydration to correctly allocate the DOM-children required to rehydrate a Suspense boundary. Currently this purposefully excludes streaming renders.
This needs a lot more tests and will probably lead to a major version of RTS and Preact (to be discussed).
The algorithm we'd use in Preact for this would entail us searching for the comment boundary, so in the most ideal scenario this would look like
```js
const excessDomChildren = [null, COMMENT_BEGIN,...theDomNodes, COMMENT_END];
```
but there will be time where it looks like 
```js
const excessDomChildren = [null, COMMENT_BEGIN, 'div', COMMENT_BEGIN, COMMENT_END, COMMENT_END];
```
due to …

Denote suspenseful components with comment markers

---

.changeset/long-ties-brake.md
src/index.js
test/compat/async.test.jsx

I ran into an issue that is very similar to https://github.com/preactjs/preact-render-to-string/pull/335, where multiple suspended children in the same Suspense boundary throw a promise that bubbles out of the render functions, resulting in `Error: the promise {} was thrown, throw an Error :)`.
```jsx
const promise = renderToStringAsync(
<ul>
<Suspense fallback={null}>
<SuspenderOne>
<li>one</li>
</SuspenderOne>
<SuspenderTwo>
<li>two</li>
</SuspenderTwo>
<SuspenderThree>
<li>three</li>
</SuspenderThree>
</Suspense>
</ul>
);
suspendedOne.promise.then(() => { void suspendedTwo.resolve();});
suspendedTwo.promise.then(() => { void suspendedThree.resolve();});
suspendedOne.resolve();
```
This only occurs when there are 3+ direct children in a Suspense boundary, rendered async, where the …

Fix rendering waterfall of suspended components in a single Suspense boundary

---

.changeset/yellow-hounds-jog.md
src/stream-node.js
test/compat/stream-node.test.js
test/compat/stream.test.js

Remix/React-Router seems to [always call `abort()` after a short timeout](https://github.com/remix-run/react-router/blob/5a1ca081ef49475ac9e23b6ea6ca6f365db58597/packages/react-router-dev/config/defaults/entry.server.node.tsx#L64-L66). This reports the following "error":
```
Error: The render was aborted by the server without a reason.
at Timeout.abort [as _onTimeout] (file:///home/ryun/Projects/tmp-react-router-preact/node_modules/preact-render-to-string/src/stream-node.js:75:4)
at listOnTimeout (node:internal/timers:594:17)
at processTimers (node:internal/timers:529:7)
```
To my understanding, this is something we can ignore if the stream has already been closed. [React does something along these lines too](https://github.com/facebook/react/blob/a0fdb6306043b9f049106e58dcec107d8dbed2b1/p …

fix: Only abort pipeablestream if not already closed

---

test/compat/index.test.jsx
test/render.test.jsx

Resolves https://github.com/preactjs/ecosystem-ci/actions/runs/13334317934/job/37245955744

Move test to compat for v11

---

benchmarks/async.js
benchmarks/lib/benchmark-lite.js
demo/src/entry-client.jsx
jsx.js
package-lock.json
package.json
src/index.js
src/jsx.js
src/lib/polyfills.js
src/lib/util.js
test/compat/async.test.jsx
test/compat/stream.test.jsx
test/render.test.jsx

This PR swaps out `eslint` with `oxlint`

chore: switch eslint -> oxlint

---

.changeset/mean-dragons-ring.md
package-lock.json
package.json
src/index.js
test/render.test.jsx
test/signals/render.test.jsx

Fixes https://github.com/preactjs/preact-render-to-string/issues/422

Detect and unwrap signal properties

---

.changeset/fifty-oranges-sip.md
package.json
src/pretty.js
test/jsx.test.jsx

Fix JSX renderer to correctly render enumerated properties

---

.changeset/rude-apes-taste.md
package-lock.json
src/pretty.js
test/pretty.test.jsx
test/render.test.jsx

`<pre>` and `<textarea>` are whitespace-sensitive. When pretty-printing, it's important to not inject extra whitespace when rendering them.
There may be more tags for which whitespace should be preserved; these are the two that I specifically know about.
Disclosure: I wrote the tests by hand and used GPT-5-Codex to help with the implementation.

Preserve whitespace for pre/textarea when pretty-printing
